#!usr/bin/env python3
import rospy

def timerCallback(event=None):
rospy.loginfo("call timmercallback function")

if __name__== "__main__":
rospy.init_node("simple_timer_py")
timer_duration=rospy.Duration(1)
rospy.Time(timer_duration ,timerCallback)
rospy.spin()
